### PR TITLE
Modernize ASDF system

### PR DESCRIPTION
**Pull request by attila-lendvai**
This eliminates an ASDF warning, too.

### CODE REVIEW

**Review by tokenrove — APPROVED** [review]
LGTM.  Thanks!

**Comment by tokenrove** [comment]
Oh, would you mind updating `.travis.yml` with the corresponding changes?  The CI tests should pass then.

**Comment by tokenrove** [comment]
Never mind; I've done this myself and pushed the tag 0.9.6 for the new release.  Thanks.

**Comment by attila-lendvai** [comment]
oh, i forgot about travis, sorry. and thanks for the merge!

**Pull request closed without merging**
