### PR TITLE
Add file attributes for clean Genera compile.

### PR DESCRIPTION
**Pull request by Symbolics**
Genera requires file attributes to be set for proper compilation. These are set by the first line of the file. No code changes required.

Also added a .gitignore file.

### CODE REVIEW

**Comment by tokenrove** [comment]
Thanks!  We won't take the `.gitignore` file, as most of these entries are probably better as a global `.gitignore` configuration local to your system — e.g. editor autosave files, Lisp-system-specific fasl suffixes.

I would accept a patch with just the file attribute lines, if you wouldn't mind restructuring the commit message to follow https://chris.beams.io/posts/git-commit/.  Is there any documentation still around that you could link me to that explains what's necessary in these attribute lines for Genera?  I see a similar, but different, header in the `series` package, for example.

**Comment by Symbolics** [comment]
No worries. After reading, agreed that .gitignore should be a site local configuration. I have removed it. For commit messages, I appreciate that link. It makes good sense, thank you. How about this as a commit message:

    "Genera requires file attributes instead of (in-package)"

If that commit message is fine, I can 'force' push over the last commit message, but not apparently two of them without some sorcery. Do you have links or commands to write over both commit messages? Or, if reworking the last commit message is fine, we're good to go. Git is not my strong point.

There is documentation in the system itself (DocumentExaminer) on file attributes, but apart from some archive.org PDF manuals, I have not found any at large. Briefly, the attribute line sets certain properties of the file when it is read, and these are used when compiling and loading. For example 'Syntax' specifies one of the (at least) three dialects of LISP that Genera runs:
```
LISP             -> ZetaLisp
COMMON-LISP      -> CLtL2
ANSI-COMMON-LISP -> ANSI LISP
```
A common problem is people putting COMMON-LISP (CltL2) in for Syntax. It's close enough that it will sometimes work, but often introduces subtle bugs. This is probably partly because emacs also uses this line to set some editing modes and people do not realize that they have real meaning to some compilers and are not just cosmetic.

The Package attribute is equivalent to (in-package). Genera honors (in-package), but not until _after_ compiling and loading the file using the Package attribute. If the Package attribute wasn't set, it uses the current package, which is often the last file compiled, so you end up with all the definitions being loaded into packages off by one. There is an open bug for this, as the ANSI spec says compile & load should rebind *package* & *read-table* to the values they had before processing the file.

Okay, that wasn't exactly brief, but at least it was (mostly) complete.

**Comment by tokenrove** [comment]
Thanks a lot!  I'd suggest a message like:

```
Add file attributes for Genera

Genera requires file attributes to be set for proper compilation. These are set by the first line of the file.
Briefly, the attribute line sets certain properties of the file when it is read, and these are used when
compiling and loading. For example 'Syntax' specifies one of the (at least) three dialects of LISP that
Genera runs:

LISP -> ZetaLisp
COMMON-LISP -> CLtL2
ANSI-COMMON-LISP -> ANSI LISP

A common problem is people putting COMMON-LISP (CltL2) in for Syntax. It's close enough that it will
sometimes work, but often introduces subtle bugs. This is probably partly because emacs also uses this
line to set some editing modes and people do not realize that they have real meaning to some compilers
and are not just cosmetic.

The Package attribute is equivalent to (in-package). Genera honors (in-package), but not until after
compiling and loading the file using the Package attribute. If the Package attribute wasn't set, it uses the
current package, which is often the last file compiled, so you end up with all the definitions being loaded
into packages off by one. There is an open bug for this, as the ANSI spec says compile & load should
rebind package & read-table to the values they had before processing the file.
```
(except with lines wrapped before 80 columns, which I can't easily do in this silly web form editor)

This includes the short message in the imperative form, as well as a detailed message that provides the background around the commit so when someone `git blame`s to figure out what that strange comment line is, they learn what you've just taught me.

Since the branch from which you've opened the PR is used by you alone, you can force push to it; I recommend using an interactive rebase.  Magit in emacs, if you're using it, makes it fairly easy.

Also, is `Base: 10` required?  And can we write `Lisp` instead of `LISP` for the mode?

**Comment by Symbolics** [comment]
Okay, I think I've got the git commits fixed up. Appreciate the pointer to magit and rebasing. It was a worthwhile diversion.

As for `Base: 10`, you can omit it, but then a warning is thrown on each file, so I've left it. LISP->Lisp is no problem, and that is part of the new commit.

**Comment by tokenrove** [comment]
Looks great!  Thanks!  (Sorry about the CI failure; I'll get to that later)

**Pull request merged**
